spring.application.name=be
spring.data.mongodb.uri=mongodb+srv://dev-team:QTMA187dBMichael@studytool.ywyw4.mongodb.net/?retryWrites=true&w=majority&appName=studytool
spring.data.mongodb.database=appdata
jwt.secret=asdf987a6sdfa9s8df76a9sdf
openaikey=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
# server.port=8443
# server.ssl.key-store-type=PKCS12
# server.ssl.key-store=classpath:keystore.p12
# server.ssl.key-store-password=9621
# server.ssl.key-alias=tomcat
server.port=8080
server.ssl.enabled=false