spring.application.name=be
spring.data.mongodb.uri=mongodb+srv://dev-team:QTMA187dBMichael@studytool.ywyw4.mongodb.net/?retryWrites=true&w=majority&appName=studytool
#spring.data.mongodb.uri=mongodb+srv://kaynelee:eTSCadt1uT9xQB0n@cluster0.1htyk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=appdata